# Generated by Django 3.0.3 on 2021-02-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210131_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='UPLOAD_MRI_IMAGE',
            new_name='UPLOAD_DIGIT_IMAGE',
        ),
    ]
